### ISSUE TITLE
Arduino nano iot as USB OTG host

### ISSUE THREAD

**Issue by sdetweil** [rkl099/Appinventor-SerialOTG#10]
I need to use nano iot as USB host for another board

using an otg cable micro connector on both ends
https://www.amazon.com/dp/B07CKW6RYD/ref=cm_sw_r_apan_glt_i_5MMN7ZQV0RE498XHFJAH?_encoding=UTF8&psc=1

nano supports host mode

apologize, I don't know what AppInventor means

**Comment by rkl099** [comment]
Appinventor is a block programming environment for Android devices, see https://appinventor.mit.edu/.
SerialOTG is an extension for Appinventor to allow serial communication with other devices. (now also BT and WIFI)
It is based on a debugged, modified and extended Physicaloid Java library that needs an Android runtime. I don't know if this is available on an nano iot, even if it uses an Arm processor.
