### ISSUE TITLE
Stop bits configuration

### ISSUE THREAD

**Issue by Felan412** [rkl099/Appinventor-SerialOTG#13]
Requires 38400 8N2 configuration. How can I make two stop bits?

**Comment by rkl099** [comment]
This is not implemented in the extension (yet), even if its included in the Physicaloid library.  Mainly because it's difficult to test.
It can be added for transmit, but it will not be tested for in the receive function.
It's easy to implement if you need it, but time consuming to test for all usb-serial adapters

**Comment by rkl099** [comment]
I have added support for Physicaloid library stopbits in SerialOTG.
StopBits(n) and n=StopBits. Value n 0=>1, 1=>1.5, 2=>2 stopbits .
Please test and report what adapter you are using (or selected driver).
(Adapter type can be tested with a Linux system and terminal cmd dmesg) The extension can be found at github.com/rkl099/Appinventor_Debug

**Comment by Felan412** [comment]
Adapter: CP2102 USB To UART Bridge Controller.
When checked by a logic analyzer, there is no difference between 1; 1.5; 2 stop bits. It is always 1 stop bit.

**Comment by rkl099** [comment]
Made a test program and checked the timing of output characters. All adapters seems to change nr of stopbits 1 or 2 including CP2102. the use of 1.5 stopbits is restricted depending on adapter and baudrate. Only PL2303 sets 1.5 stopbits at 9.6 kbaud. Found a problem in the CH340 driver. Selection of 0 (1 stopbit) kept the previous selection. Now updated to select 1 stopbit.
(CDC ACM not tested). With the test program I can measure timing for each character startbit-startbit and total time for 1000 characters.

**Comment by Felan412** [comment]
The problem seems to be that changing the stop bit before the port is open (call SerialOTG1.open) has no effect. If change the value after opening the port (for example, using a text field and a button), then everything works fine.

**Comment by rkl099** [comment]
Thank you for testing and finding that problem. I have updated the extension so you can update stopbits before open, like other properties. You should also be able to change stopbits as a property in AI designer view

**Comment by Felan412** [comment]
Checked, now everything works as it should. Thank you for your solution. I think that the issue can be closed.
