### ISSUE TITLE
Upload firmware to esp32

### ISSUE THREAD

**Issue by ghost** [rkl099/Appinventor-SerialOTG#18]
Hi, I want to use this extension to upload firmware to esp32 via ch340, what file format is supported,ino or bin? It possible please add .bin support, great extension none the less.

**Comment by rkl099** [comment]
The only formats supported are Microchip STK500/STK500V2 used by the Arduino loader to flash programs. Don't care about the file extension, but normally .hex from the Arduino tools.

**Comment by ghost** [comment]
can i flash the file intended for esptool/esphome flasher?

**Comment by rkl099** [comment]
Don't know the format.
