### ISSUE TITLE
Slow Data Transmission with FTDI USB to Serial Adapter in SerialOTG V1.5

### ISSUE THREAD

**Issue by hdtran2004** [rkl099/Appinventor-SerialOTG#19]
Hi @rkl099,
Firstly, I want to express my gratitude for your work on this extension; it's been instrumental in the development of my application.

**Issue Description:**
I'm encountering a performance issue in my application where data transmission to an end device is significantly slower than expected. 
When sending a large text file (6100 lines, ~40 characters per line), the transmission is unusually slow.
It took about 20 minutes for the entire file to be sent.
I've observed a consistent delay of approximately 3ms between each byte of data, as shown in the attached capture.

**Setup:**
- FTDI USB to serial convertor (Chipset is FT232RQ)
- Communication settings: 38400bps, 1-Stop bit
- Test device: Pixel 7a running Android 14
- SerialOTG V1.5

**Expected Behavior:**
The data should transmit at a regular pace without such delays, especially given the baud rate and setup.

**Actual Behavior:**
Experiencing significant delays between each byte, leading to an overall slow transmission.

**Attachments:**
Transmission waveform
![Screenshot 2023-11-14 032004](https://github.com/rkl099/Appinventor-SerialOTG/assets/46913266/44e68341-1d0e-4d20-8cf5-abc894b0ba26)

Could this issue be related to the driver? Any assistance or guidance you can provide would be greatly appreciated.

**Comment by rkl099** [comment]
Do your example with WriteBytes (MIT forum) make  a list of length>1 ?
I looked at the code and all bytes from the list up do the device max length should be in one USB transfer to the USB-Serial converter.

**Comment by hdtran2004** [comment]
I can confirm that the list length is 15 bytes (For testing I'm sending a static string), I modified the send block to log the length to confirm as per below,
![image](https://github.com/rkl099/Appinventor-SerialOTG/assets/46913266/3e083c5a-22ae-49c2-a0dc-6350c02a2b92)

**Comment by rkl099** [comment]
For some reason is the write_size set to 1 in the driver (physicaloid) for  FTDI. So what you see is a function of the driver and even if you use lists will it result i bulk transfers of just one byte! I need to study the spec for different FTDI chips (and study some other drivers like Linux) to change this and also do some testing. It will take some time, but I will let you know the result.
CH34x has a write size of 64 bytes, if you want to test another chip

**Comment by hdtran2004** [comment]
Thank you for the confirmation, greatly appreciate your time.
Unfortunately, I'm stuck with FTDI.
