### ISSUE TITLE
BT upload - Getting .hex file from different source

### ISSUE THREAD

**Issue by mister0wl** [rkl099/Appinventor-SerialOTG#21]
Hello,
at first, thank you for your work. I'd like to use SerialOTG_BT_WIFI.aia for uploading to my Nano 328pb + HC06 setup. However, I would like to download the .hex file from the Internet. The .Upload() method only accepts a board type + filepath. Would it be possible to add a method to accept board type + the content of a .hex file? 

Also, I know that the Atmel328pb uses different signature bytes (0x1e 0x95 0x16) for identification, I don't know if it matters during the upload as I don't see your code (of course I compile the Arduino code for the PB board so my hex file is OK).

Thank you,

**Comment by rkl099** [comment]
Do you mean including the contents of the .hex as text after the upload command? Then it is better to download or copy it from the internet (and convert it to hex data in a programing editor if necessary)  before upload.
I don't think the signature byte is significant here. Board type is used to identify protocol (STK500 or STK500V2), memory size and baudrate. The programming of the chip is handled by the Arduino bootloader.

**Comment by mister0wl** [comment]
Hello,
yes, I thought instead of passing the file path, I could pass the hex data as text. In my project I don't have control over the Android devices, and there is a demand that the update should not be written to the Android device, for security reasons. I have control over a server where I can convert the .hex file to any format (but I chose Intel .hex format as it's very easy to read and send for 8 bit microcontrollers). For my purpose, your .upload() method is monolithic. I could do the conversion and protocol handling myself, using only read and write methods; but then the benefit of this extension is lost for me. At first I tried to implement an uploader in AI2 using the built-in Bluetooth client component but the scheduler of the Clock component is too loose for the STK500v2 protocol and the upload failed if the .hex file is bigger than 10kB. That's why I'd like to try my luck with your nice extension. :-) If that's not possible, I see no other option but to write an extension by myself and I'd like to save some work if it's an easy change for you to implement this new method.

**Comment by rkl099** [comment]
This is a part 0of the original Physicaloid library.  I made some updates in the code to make it work 2 years ago. It seems to be to much work to implement the requested change in the library and the extension.
Ps: can you access the hex-file over the network or on a USB or SD card?

**Comment by mister0wl** [comment]
OK, now I  see. I can access the file over the network; I'll download it to some shared directory, pass it to the upload() method then delete the file from the device. I hope that'll be OK for security. Thank you for your answers!
