### ISSUE TITLE
micro:bit and Adafruit CLUE support

### ISSUE THREAD

**Issue by tguneysu** [rkl099/Appinventor-SerialOTG#3]
Hi rkl099,
Thank you for a great addition to the AI2.

Two questions:

1.
I am using the extension with micro:bit connected to the Android phone over an OTG & USB cables.
Below incidents are while in Companion op mode.
It works the first time AI2 Companion is started, pops up Serial Permission screen and all is fine.

On subsequent disconnect and connects, the Serial permission is never displayed, and the program does not open the USB, even though it is initialized.

Do you know why that is?

Even if I reset the APP defaults, it still does not work more than one connection attempt.

I understand this might be something in the Android, but still would like to know how to overcome it.
I am testing with various Androids, all with the same result: 
NOTE4 & S5 with A6.0.1, NOTE@ with A4.4.2

NOTE: I tested it after creating an APK, and it works OK everytime. So it is only problematic in the Companion mode.

2.
Another device, Adafruit CLUE, does not work at all with this extension. What can I do to help, so this device serial will also be supported ? 

Thanks

**Comment by rkl099** [comment]
Some hints how to solve your problems.
Close your serial connection before you make any changes to your app  or refresh the screen.
If you need to reset the connection from the PC, remove the current instance of the Ai2 Companion in the phone. Do not just restart with the companion icon.

For Adafruit CLUE, try my debug version Appinventor-SerialOTG_Debug with support for Adafruit Feather M0, Vendor ID 239A (and some other devices). This is probably the same as used for CLUE. If not get Vendor ID and Product ID and  then I can add support for this device.
This will later be included in the release version.
Please let me know if this solves any of your problems.

**Comment by tguneysu** [comment]
Hello RLK099,

I tried using your debug version and when trying to import into AI2, I got the following error:
![image](https://user-images.githubusercontent.com/6268038/109352182-77c33080-788b-11eb-85d7-ab8bbe929413.png)

I simply tried importing the AIX file, like i do with the other ones. If this version required some other handling, I do not know it.

As far as the other suggestions goes, I understand the point. But since the compiled version works OK and I only encounter it during repetitive disconnect and connects, I will manage it. So no bother.

Looking forward to testing the CLUE version , once you tell what is wrong with the extension.

Thanks, TG

**Comment by rkl099** [comment]
Just downloaded and imported the extension without any problems. I'm using Linux/Firefox for the download and import to AI2, but I don't think that this matters.

**Comment by tguneysu** [comment]
OK, It must have been a bad download. I downloaded again and it updated. Thx.
I will test tonight and report.

**Comment by tguneysu** [comment]
Thank you very much !
The debug version works great with Adafruit CLUE.

**Comment by rkl099** [comment]
Glad to hear that it's working now!
