### ISSUE TITLE
Using the USB port while in Genymotion Emulator

### ISSUE THREAD

**Issue by tguneysu** [rkl099/Appinventor-SerialOTG#4]
Hi RKL999,
I was wondering if the SerialOTG would work while I run my generated APK in the Genymotion Emulator?
It has USB support, and VirtualBox that it runs , is able to filter the PC Host USB ports.
When I run the APP it comes up fine, and the VirtualBox is set to select microBit USB connection.
However, I cannot open the port.
The reason I am asking this is, I would like to demo the AI2 software running on the PC in emulator, so I can share the display.
Would appreciate your assessment of the attempt.
Thx.

**Comment by rkl099** [comment]
I have no idea!
Some general advice’s
Use an app that checks what's connected as USB OTG.
Some arm-devices needs a program that activates the serial port. Otherwise they will not be detected as a serial device. Is the Micro:bit working when connected to a real android device?
Can you cast the android screen for demonstrating purpose? But I don’t know if you can cast to a program in your pc.

**Comment by tguneysu** [comment]
Just to close the loop, I wanted to let you know that I was able to use the Genymotion emulator and your SerialOTG without a problem. However, it only work with Adafruit CLUE device. None of the other devices worked, even though they worked great in the gen'ed APK. No problem though. I got my demo done in excellent quality.

**Comment by rkl099** [comment]
Glad to hear that it's working for you. It's always interesting to hear
about different applications.

Den fre 5 mars 2021 kl 13:40 skrev Turgut ***@***.***>:

**Comment by rkl099** [comment]
Glad to hear that it's working for you. It's always interesting to hear about different applications.

**Comment by ronaldbenve** [comment]
I didn't get it working with STM32 Bluepill (STM32F103), it would be nice.
VID : 0483 STMicroele
PID : 5740 STM32 Virtual Com Port
On my phone (Samsuns Galaxy S7) Bluepill works with Serial USB Terminal.
