### ISSUE TITLE
Bluepill STM32F103 support

### ISSUE THREAD

**Issue by ronaldbenve** [rkl099/Appinventor-SerialOTG#7]
I didn't get it working with STM32 Bluepill (STM32F103), it would be nice.
VID : 0483 STMicroele
PID : 5740 STM32 Virtual Com Port
On my phone (Samsuns Galaxy S7) Bluepill works with Serial USB Terminal.

**Comment by rkl099** [comment]
I did a quick check of the VID list and VID : 0483 should already be included.
I will test with a Bluepill after the summer.
Please check DTR/RTS (and baudrate/parity) 
(ref https://community.appinventor.mit.edu/t/using-serial-with-ftdi/14136/82)

See also "Some notes on SerialOTG" in SerialOTG.pdf
