### ISSUE TITLE
Connection lost after 5seconds

### ISSUE THREAD

**Issue by DeveloKing** [rkl099/Appinventor-SerialOTG#8]
hi. I am using to connect to a arduino nano ch340, 
it  connects at firt but disconnects after 5 seconds and i can´t reconnect.
Any idea whatit can be?

**Comment by rkl099** [comment]
What do you mean with “disconnects”?
Can you give some more information about your setup and application?

**Comment by DeveloKing** [comment]
Sorry for the long time without answering. 
It simply stopped sending information to the arduino, but them I had a timer testing if it was connected and the problem disapeared.
